---
title: "3. Complete analysis Kassaw et al."
author: "Jelyn Gerkema"
date: "2023-10-16"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## 0. Set up
```{r set up}
source("src/settings2.R")
source("src/functions.R")

```

## 1.Clean data


### 1.1 Kassaw et al. 2023
```{r clean data}

kassaw_veg <- read_csv("data/raw/Kassaw et al. 2023/species abundance.csv") %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column(var = "Name") %>%
  mutate(Name = gsub("_", " ", Name)) %>%
  mutate(Name = recode(Name, "Acacia abyssnica" = "Acacia abyssinica",
                       "Albizia gumifera" = "Albizia gummifera",
                       "Crateva adonsonia" = "Crateva adansonii",
                       "Olea europea subsp.cuspidata" = "Olea europaea subsp. cuspidata",
                       "Senna serguana" = "Senna singueana",
                       "Terminalia laxifolia" = "Terminalia laxiflora",
                       "Ziziphus spina" = "Ziziphus spina-christi")) %>%
  column_to_rownames(var = "Name") %>%
  t() %>%
  as.data.frame() %>%
  select(order(colnames(.)))

kassaw_trait <- read_csv("data/raw/Kassaw et al. 2023/trait data.csv") %>%
  rename(Name = species) %>%
  select(order(colnames(.))) %>%
  mutate(Name = gsub("_", " ", Name)) %>%
    mutate(Name = recode(Name, "Acacia abyssnica" = "Acacia abyssinica",
                       "Albizia gumifera" = "Albizia gummifera",
                       "Crateva adonsonia" = "Crateva adansonii",
                       "Olea europea subsp.cuspidata" = "Olea europaea subsp. cuspidata",
                       "Senna serguana" = "Senna singueana",
                       "Terminalia laxifolia" = "Terminalia laxiflora",
                       "Ziziphus spina" = "Ziziphus spina-christi")) %>%
  relocate(Name) %>%
  arrange(Name)

kassaw_species_list <- colnames(kassaw_veg)

kassaw_trait_fd <- kassaw_trait %>%
  column_to_rownames(var = "Name") 

kassaw_trait <- kassaw_trait %>%
  mutate(across(where(is.numeric), ~ c(scale(., center = F)))) 

traitlist <- sort(c( "LA", "LDMC", "LT", "SLA"))
cwm_names <- paste0(traitlist, "_cwm")
cwv_names <- paste0(traitlist, "_cwv")

trait_information <- lst(traitlist, cwm_names, cwv_names)

``` 


## 5. Perform calculations
```{r calculations }

kassaw_processed_specieslvl <- cats_preparation(input_veg = kassaw_veg, input_trait = kassaw_trait, cutoff_value =  0.8, trait_information = trait_information,
                                             trait_detail = "Study")

mean_dist <- calculate_mean_dist(kassaw_veg, kassaw_processed_specieslvl)

FD <- dbFD(kassaw_trait_fd, kassaw_veg, stand.x = T)

FD_df <- data.frame(FEve = FD$FEve,
        FDiv  = FD$FDiv,
        FRic = FD$FRic,
        RaoQ = FD$RaoQ,
        qual.FRic = FD$qual.FRic) %>%
  rownames_to_column(var = "Plot_code")

diversity_info <- kassaw_processed_specieslvl[["relative_abundances"]][["matrix4traits_prop"]] %>% 
  as.data.frame() %>% 
  mutate(shannon = diversity(.[,1:ncol(.)], index = "shannon", MARGIN = 1, base = exp(1)),
         simpson = diversity(.[,1:ncol(.)], index = "simpson", MARGIN = 1, base =exp(1)),
         species_richness = specnumber(.[,1:ncol(.)], MARGIN = 1),
         empty_states = ncol(kassaw_processed_specieslvl[["relative_abundances"]][["matrix4traits_prop"]]) - species_richness,
         meta_size = ncol(kassaw_processed_specieslvl[["relative_abundances"]][["matrix4traits_prop"]])) %>%
  select(shannon, simpson, species_richness, empty_states, meta_size) %>% # base = exp(1) gives the shannon index a log e base
  rownames_to_column(var = "Plot_code") %>% 
  full_join(mean_dist) %>%
  full_join(FD_df)


```



## 6. Cats model
```{r cats calculations}

#Determines amount of cores, substract four to keep to pc free for other processes.


if(foreach::getDoParRegistered() != TRUE){
  n_cores <- parallel::detectCores() - 5 

my_cluster <- makeSOCKcluster(n_cores)

registerDoSNOW(cl = my_cluster)} # check if cluster is set up


kassaw_cats <- cats_calculations(kassaw_processed_specieslvl, trait_information,
                                 trait_detail = "Study") %>%
  mutate(study = "Kassaw")


kassaw_figure <- cats_visualisation(kassaw_cats) %>%
  mutate(study = "Kassaw")

save(kassaw_processed_specieslvl, kassaw_figure, kassaw_species_list, kassaw_cats,
 file = "data/processed/kassaw_calculations.RData")

ggplot(kassaw_figure, aes(x = species_richness, y = KLR2)) +
  geom_point() +
  facet_wrap(~Deviance) + 
  theme_classic() +
  geom_smooth(method = "lm") + 
  labs(title = "The relationship between species richness and the CATS decomposition - Kassaw et al. 2022",
       x = "Species richness") +
  geom_hline(yintercept = 0, linetype = 2) +
   coord_cartesian(ylim = c(-0.2, 1)) +
  scale_y_continuous(breaks = c(-0.2, 0,0.2, 0.4, 
    0.6,  0.8,  1
  )) 

ggplot(kassaw_figure, aes(x = mean_dist, y = KLR2)) +
  geom_point() +
  facet_wrap(~Deviance) + 
  theme_classic() +
  geom_smooth(method = "lm") + 
  labs(title = "The relationship between plot dissimilarity and the CATS decomposition - Kassaw et al. 2023",
       x = "Average Bray-Curtis index value") +
  geom_hline(yintercept = 0, linetype = 2) +
   coord_cartesian(ylim = c(-0.2, 1)) +
  scale_y_continuous(breaks = c(-0.2, 0,0.2, 0.4, 
    0.6,  0.8,  1
  )) 






```
