---
title: "3. Complete analysis Jäschke et al. 2019."
author: "Jelyn Gerkema"
date: "2023-06-20"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## 0. Set up
```{r set up}
source("src/settings2.R")
source("src/functions.R")

```

## 1.Clean data


### 1.1 Jäschke et al. 2019
```{r clean data}

jaschke <- read_excel("data/raw/Jäschke et al. 2019/PademosTibetTraitData-Dryad2019.10.25.xlsx", 
    skip = 1) %>%
  rename(Plot_code = Plot, cover = `Cover_%`, Name = Species,
         CN = `plant_C/N`, Height = CanoH_cm, SLA = `SLA_mm2/mg` ) %>%
  mutate(Name = recode(Name, "Elymus dura" = "Elymus durus",
                       "Ixeris chinensis ssp versicolor" = "Ixeris chinensis subsp. versicolor",
                       "Potentilla parvifollia" = "Potentilla parvifolia",
                       "Convolvulus amanii" = "Convolvulus ammannii"))

jaschke_veg <- jaschke %>%
  select(c(Plot_code, cover, Name)) %>%
  pivot_wider(values_from = cover, names_from = Name) %>%
  replace(is.na(.), 0) %>%
  column_to_rownames(var = "Plot_code") %>%
  select(order(colnames(.)))


jaschke_veg_temp <- jaschke %>%
  select(c(Plot_code, cover, Name)) %>%
  pivot_wider(values_from = cover, names_from = Name) %>%
  replace(is.na(.), 0) %>%
  pivot_longer(cols = 2:ncol(.), values_to = "cover", names_to = "Name")
  
jaschke_species_list <- colnames(jaschke_veg)

jaschke_trait <- jaschke %>%
  select(c(Plot_code, Name, CN, Height, SLA)) %>%
  full_join(jaschke_veg_temp) %>%
  group_by(Name) %>%
  mutate(across(where(is.numeric), ~replace_na(., mean(., na.rm = TRUE)))) %>%
  select(-c(cover)) %>%
  ungroup() %>%
  select(order(colnames(.))) %>%
  relocate(Plot_code, Name) %>%
  arrange(Name) 

jaschke_trait_fd <- jaschke_trait

jaschke_trait <- jaschke_trait %>%
  mutate(across(where(is.numeric), ~ c(scale(., center = F)))) 
  

traitlist <- sort(c("CN", "Height", "SLA" ))
cwm_names <- paste0(traitlist, "_cwm")
cwv_names <- paste0(traitlist, "_cwv")

trait_information <- lst(traitlist, cwm_names, cwv_names)


``` 


## 5. Perform calculations
```{r calculations }

jaschke_processed_specieslvl <- cats_preparation(input_veg = jaschke_veg, input_trait = jaschke_trait, cutoff_value =  0.8, trait_information = trait_information,
                                                 trait_detail = "Plot")

mean_dist <- calculate_mean_dist(jaschke_veg, jaschke_processed_specieslvl)

FD_df <- calculate_FD_plotlvl(jaschke_processed_specieslvl, jaschke_veg, jaschke_trait_fd)

diversity_info <- jaschke_processed_specieslvl[["relative_abundances"]][["matrix4traits_prop"]] %>% 
  as.data.frame() %>% 
  mutate(shannon = diversity(.[,1:ncol(.)], index = "shannon", MARGIN = 1, base = exp(1)),
         simpson = diversity(.[,1:ncol(.)], index = "simpson", MARGIN = 1, base =exp(1)),
         species_richness = specnumber(.[,1:ncol(.)], MARGIN = 1),
         empty_states = ncol(jaschke_processed_specieslvl[["relative_abundances"]][["matrix4traits_prop"]]) - species_richness,
         meta_size = ncol(jaschke_processed_specieslvl[["relative_abundances"]][["matrix4traits_prop"]])) %>%
  select(shannon, simpson, species_richness, empty_states, meta_size) %>% # base = exp(1) gives the shannon index a log e base
  rownames_to_column(var = "Plot_code") %>%
  full_join(mean_dist) %>%
  full_join(FD_df)


```



## 6. Cats model
```{r cats calculations}

jaschke_cats <- cats_calculations(jaschke_processed_specieslvl, trait_information,
                             trait_detail = "Plot") %>%
  mutate(study = "Jäschke")


jaschke_figure <- cats_visualisation(jaschke_cats) %>%
  mutate(study = "Jäschke")

save(jaschke_processed_specieslvl, jaschke_figure, jaschke_species_list, jaschke_cats, 
  file = "data/processed/jaschke_calculations.RData")

ggplot(jaschke_figure, aes(x = species_richness, y = KLR2)) +
  geom_point() +
  facet_wrap(~Deviance) + 
  theme_classic() +
  geom_smooth(method = "lm") + 
  labs(title = "The relationship between species richness and the CATS decomposition - Jäschke et al., 2019",
       x = "Species richness") +
  geom_hline(yintercept = 0, linetype = 2) +
   coord_cartesian(ylim = c(-0.2, 1)) +
  scale_y_continuous(breaks = c(-0.2, 0,0.2, 0.4, 
    0.6,  0.8,  1
  )) 

ggplot(jaschke_figure, aes(x = mean_dist, y = KLR2)) +
  geom_point() +
  facet_wrap(~Deviance) + 
  theme_classic() +
  geom_smooth(method = "lm") + 
  labs(title = "The relationship between plot dissimilarity and the CATS decomposition - Jäschke et al., 2019",  
       x = "Average Bray-Curtis index value") +
  geom_hline(yintercept = 0, linetype = 2) +
   coord_cartesian(ylim = c(-0.2, 1)) +
  scale_y_continuous(breaks = c(-0.2, 0,0.2, 0.4, 
    0.6,  0.8,  1
  )) 



```
