---
title: "3. Complete analysis Kassaw et al."
author: "Jelyn Gerkema"
date: "2023-10-16"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## 0. Set up
```{r set up}
source("src/settings2.R")
source("src/functions.R")

```

## 1.Clean data


### 1.1 
```{r clean data}

jager_trait <- read_csv("data/raw/Jager et al. 2014/speciestraits.csv")

species_list <- read_excel("data/raw/Jager et al. 2014/speciescode_list.xlsx")


jager_veg <- read_csv("data/raw/Jager et al. 2014/speciesbasalarea.csv") %>%
  pivot_longer(cols = 2:ncol(.), values_to = "BA", names_to = "species") %>%
  full_join(species_list) %>%
  select(-c(species)) %>%
  pivot_wider(values_from = BA, names_from = Name) %>%
  column_to_rownames(var = "plot") %>%
  select(order(colnames(.)))

jager_trait <- jager_trait %>%
  full_join(species_list) %>%
  rename(LT = leafthick, SLA = sla, LDMC = ldmc, WD = wood, Height = height, 
         SM = `seed mass`, BT = bark, relBT = `relative bark thickness`) %>%
  select(-c(species)) %>%
  mutate(BT = BT + 0.00001,
         relBT = BT + 0.0001) %>%
  select(order(colnames(.))) %>%
  relocate(Name) %>%
  arrange(Name)

jager_trait_fd <- jager_trait %>%
  column_to_rownames(var = "Name") 

jager_trait <- jager_trait %>%
  mutate(across(where(is.numeric), ~ c(scale(., center = F))))  

jager_species_list <- colnames(jager_veg)

traitlist <- sort(c("LT", "BT", "SLA", "leafden", "LDMC", "tdmc", "WD", "relBT", 
                    "leafn", "leafp", "littern", "litterp", "Height", "SM"))
cwm_names <- paste0(traitlist, "_cwm")
cwv_names <- paste0(traitlist, "_cwv")

trait_information <- lst(traitlist, cwm_names, cwv_names)

``` 


## 5. Perform calculations
```{r calculations }

jager_processed_specieslvl <- cats_preparation(input_veg = jager_veg, 
                                              input_trait = jager_trait, cutoff_value =  0.8, 
                                              trait_information = trait_information,
                                            trait_detail = "Study")

mean_dist <- calculate_mean_dist(jager_veg, jager_processed_specieslvl)

FD <- dbFD(jager_trait_fd, jager_veg, stand.x = T)

FD_df <- data.frame(FEve = FD$FEve,
        FDiv  = FD$FDiv,
        FRic = FD$FRic,
        RaoQ = FD$RaoQ,
        qual.FRic = FD$qual.FRic) %>%
  rownames_to_column(var = "Plot_code")

diversity_info <- jager_processed_specieslvl[["relative_abundances"]][["matrix4traits_prop"]] %>% 
  as.data.frame() %>% 
  mutate(shannon = diversity(.[,1:ncol(.)], index = "shannon", MARGIN = 1, base = exp(1)),
         simpson = diversity(.[,1:ncol(.)], index = "simpson", MARGIN = 1, base =exp(1)),
         species_richness = specnumber(.[,1:ncol(.)], MARGIN = 1),
         empty_states = ncol(jager_processed_specieslvl[["relative_abundances"]][["matrix4traits_prop"]]) - species_richness,
         meta_size = ncol(jager_processed_specieslvl[["relative_abundances"]][["matrix4traits_prop"]])) %>%
  select(shannon, simpson, species_richness, empty_states, meta_size) %>% # base = exp(1) gives the shannon index a log e base
  rownames_to_column(var = "Plot_code") %>% 
  full_join(mean_dist) %>%
  full_join(FD_df)




```



## 6. Cats model
```{r cats calculations}

#Determines amount of cores, substract four to keep to pc free for other processes.
n_cores <- parallel::detectCores() - 5 

my_cluster <- makeSOCKcluster(n_cores)

registerDoSNOW(cl = my_cluster)

foreach::getDoParRegistered() # check if cluster is set up


jager_cats <- cats_calculations(jager_processed_specieslvl, trait_information,
                               trait_detail = "Study")

jager_figure <- cats_visualisation(jager_cats) %>%
  mutate(study = "Jager")

save(jager_processed_specieslvl, jager_figure, jager_species_list, jager_cats,
 file = "data/processed/jager_calculations.RData")

ggplot(jager_figure, aes(x = species_richness, y = KLR2)) +
  geom_point() +
  facet_wrap(~Deviance) + 
  theme_classic() +
  geom_smooth(method = "lm") + 
  labs(title = "The relationship between species richness and the CATS decomposition - Jager et al. 2014",
       x = "Species richness") +
  geom_hline(yintercept = 0, linetype = 2) +
   coord_cartesian(ylim = c(-0.2, 1)) +
  scale_y_continuous(breaks = c(-0.2, 0,0.2, 0.4, 
    0.6,  0.8,  1
  )) 

ggplot(jager_figure, aes(x = mean_dist, y = KLR2)) +
  geom_point() +
  facet_wrap(~Deviance) + 
  theme_classic() +
  geom_smooth(method = "lm") + 
  labs(title = "The relationship between plot dissimilarity and the CATS decomposition - Jager et al. 2014",
       x = "Average Bray-Curtis index value") +
  geom_hline(yintercept = 0, linetype = 2) +
   coord_cartesian(ylim = c(-0.2, 1)) +
  scale_y_continuous(breaks = c(-0.2, 0,0.2, 0.4, 
    0.6,  0.8,  1
  )) 






```
