---
title: "3. Complete analysis Rolhauser et al."
author: "Jelyn Gerkema"
date: "2023-10-16"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## 0. Set up
```{r set up}
source("src/settings2.R")
source("src/functions.R")

```

## 1.Clean data


### 1.1 Rolhauser et al. 2021
```{r clean data}

species_codes <- read_excel("data/raw/Rolhauser et al. 2021/species_codes_rolhauser.xlsx", 
    sheet = "codes_fullnames") %>%
  separate(codes, into = c("sp", "Name"), sep = " - ") %>%
  mutate(Name = recode(Name, "Polygonum biflorum" = "Polygonatum biflorum"))

# Rolhauser collected frequency data. They had 189 sites, and for each site, they recorded species presence in multiple subplots. The amount of subplots howerever, differs per site. To make the plots comparable with each other, the frequency is divided by the total number of subplots. 
rolhauser_veg <- read_excel("data/raw/Rolhauser et al. 2021/Copy of Rolhauser__Waller___Tucker_J_Ecol_-_data.xlsx") %>%
  mutate(freq_new = freq/quads) %>%
  select(c(site, sp, freq_new)) %>%
  full_join(species_codes) %>%
  select(-c(sp)) %>%
  pivot_wider(names_from = Name, values_from = freq_new) %>%
  rename(Plot_code = site) %>%
  column_to_rownames(var = "Plot_code") %>%
  select(order(colnames(.)))

rolhauser_trait <- read_excel("data/raw/Rolhauser et al. 2021/Copy of Rolhauser__Waller___Tucker_J_Ecol_-_data.xlsx") %>%
  select(c(sp, SLA, VH, LCC, LS, CN, LT, LNC, LDMC)) %>%
  distinct() %>%
  full_join(species_codes) %>%
  select(-c(sp)) %>%
  rename(Height = VH) %>%
  arrange(Name) %>%
  select(order(colnames(.))) %>%
  relocate(Name)

rolhauser_trait_fd <- rolhauser_trait %>%
  column_to_rownames(var = "Name") %>%
  mutate(across(where(is.numeric), ~ c(scale(., center = T)))) # Center is true, this results in a mean of 0. This way of standardizing would not work for CATS, since all values need to be higher than 0, but for FD, this is preferred. 
  

traitlist <- sort(c( "CN", "Height", "LCC", "LDMC", "LNC", "LS", "LT", "SLA"))
cwm_names <- paste0(traitlist, "_cwm")
cwv_names <- paste0(traitlist, "_cwv")

trait_information <- lst(traitlist, cwm_names, cwv_names)

``` 


## 5. Perform calculations
```{r calculations }

rolhauser_processed_specieslvl <- cats_preparation(input_veg = rolhauser_veg, input_trait = rolhauser_trait, cutoff_value =  0.8, trait_information = trait_information,
                                                trait_detail = "Study")

mean_dist <- calculate_mean_dist(rolhauser_veg, rolhauser_processed_specieslvl)

FD <- dbFD(rolhauser_trait_fd, rolhauser_veg)

diversity_info <- rolhauser_processed_specieslvl[["relative_abundances"]][["matrix4traits_prop"]] %>% 
  as.data.frame() %>% 
  mutate(shannon = diversity(.[,1:ncol(.)], index = "shannon", MARGIN = 1, base = exp(1)),
         simpson = diversity(.[,1:ncol(.)], index = "simpson", MARGIN = 1, base =exp(1)),
         species_richness = specnumber(.[,1:ncol(.)], MARGIN = 1),
         empty_states = ncol(rolhauser_processed_specieslvl[["relative_abundances"]][["matrix4traits_prop"]]) - species_richness,
         meta_size = ncol(rolhauser_processed_specieslvl[["relative_abundances"]][["matrix4traits_prop"]])) %>%
  select(shannon, simpson, species_richness, empty_states, meta_size) %>% # base = exp(1) gives the shannon index a log e base
  rownames_to_column(var = "Plot_code") %>% 
  full_join(mean_dist) %>%
  mutate(FEve = FD$FEve,
        FDiv  = FD$FDiv,
        FRic = FD$FRic)



```



## 6. Cats model
```{r cats calculations}

#Determines amount of cores, substract four to keep to pc free for other processes.
n_cores <- parallel::detectCores() - 5 

my_cluster <- makeSOCKcluster(n_cores)

registerDoSNOW(cl = my_cluster)

foreach::getDoParRegistered() # check if cluster is set up


rolhauser_cats <- cats_calculations(rolhauser_processed_specieslvl, trait_information,
                                    trait_detail = "Study") %>%
  mutate(study = "Rolhauser")

rolhauser_figure <- cats_visualisation(rolhauser_cats) %>%
  mutate(study = "Rolhauser")

save(rolhauser_processed_specieslvl, rolhauser_figure, rolhauser_cats,
 file = "data/processed/rolhauser_calculations.RData")

ggplot(rolhauser_figure, aes(x = species_richness, y = KLR2)) +
  geom_point() +
  facet_wrap(~Deviance) + 
  theme_classic() +
  geom_smooth(method = "lm") + 
  labs(title = "The relationship between species richness and the CATS decomposition - Rolhauser et al. 2021
",
       x = "Species richness") +
  geom_hline(yintercept = 0, linetype = 2) +
   coord_cartesian(ylim = c(-0.2, 1)) +
  scale_y_continuous(breaks = c(-0.2, 0,0.2, 0.4, 
    0.6,  0.8,  1
  )) 

ggplot(rolhauser_figure, aes(x = mean_dist, y = KLR2)) +
  geom_point() +
  facet_wrap(~Deviance) + 
  theme_classic() +
  geom_smooth(method = "lm") + 
  labs(title = "The relationship between plot dissimilarity and the CATS decomposition - Rolhauser et al. 2021",
       x = "Average Bray-Curtis index value") +
  geom_hline(yintercept = 0, linetype = 2) +
   coord_cartesian(ylim = c(-0.2, 1)) +
  scale_y_continuous(breaks = c(-0.2, 0,0.2, 0.4, 
    0.6,  0.8,  1
  )) 






```
