---
title: "0.Preprocessing"
author: "Jelyn Gerkema"
date: "2023-06-20"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## 0. Set up
```{r set up}
source("src/settings.R")
source("src/functions.R")
```

## 1.Clean data

### 1.1 Chalmandrier et al. 2022
```{r clean data}

# The data of Chalmandrier has already been filtered in their own analysis. 
# I use their raw cover and trait data but I extract their selected plot_codes so I can filter the raw data

load("data/raw/Chalmandrier et al. 2022/data/data_ready.Rdata")

plot_code_vector <- env_p %>%
  pull(QuadID)

# Remove unnecessary objects from the global environment
rm(data)
rm(obs.comm)
rm(pdf_species)
rm(t.avg)
rm(env_p)

# Cleaning the vegetation data so it can be used to filter the trait data. 
# Some plots have traits but no cover data. The traits are used to impute missing values
# but the plots are afterwards removed. Some plots have cover but no traits, these traits
# are imputed by taking the species average across all plots. Some plots have cover and multiple
# trait values for some species. For those plots, the average species value is taken. In addition,
# trait data is created for the empty states,  ie. absent species in a certain plot. 

chalmandrier_veg_cleantemp <- read_csv("data/raw/Chalmandrier et al. 2022/data/community.cover.23sp.csv") %>%
  filter(QuadID %in% plot_code_vector) %>%
  rename(Plot_code = QuadID) %>%
  pivot_longer(cols = 2:ncol(.), values_to = "cover", names_to = "Name") # %>%
  #filter(cover != 0)


chalmandrier_trait <- read_csv("data/raw/Chalmandrier et al. 2022/data/kettleholedata.23sp.csv") %>%
  filter(QuadID %in% plot_code_vector) %>%
  select(QuadID, poros, height, sla, species) %>%
  rename(Plot_code = QuadID, Name = species) %>%
  group_by(Plot_code, Name) %>%
  summarise(across(where(is.numeric), ~mean(., na.rm = TRUE))) %>% #In some quadrants, some species have multiple recordings, the average is taken here. 
  ungroup() %>%
  full_join(chalmandrier_veg_cleantemp) %>%
  group_by(Name) %>%
  mutate(across(.cols = c(poros, height, sla),  
            ~replace_na(., 
                        mean(., na.rm = TRUE)))) %>% # The NA's are filled up by the species mean
  ungroup() %>%
  arrange(Name) %>%
  drop_na(cover) %>%
  drop_na(poros) %>% # Some cases have no abundance data and no trait data, by dropping NA's 
  # of one of the trait values, these cases (n = 134) are removed as well. 
  select(-c(cover)) %>%
  relocate(Plot_code, Name, height, poros, sla) #%>%
  #mutate(across(where(is.numeric), ~ c(scale(., center = FALSE)))) 

traitlist <- c("height", "poros", "sla")
cwm_names <- paste0(traitlist, "_cwm")
cwv_names <- paste0(traitlist, "_cwv")

trait_information <- lst(traitlist, cwm_names, cwv_names)

# Cleaning the vegetation data so it can be used in the calculate_abundance function
chalmandrier_cover <- read_csv("data/raw/Chalmandrier et al. 2022/data/community.cover.23sp.csv") %>%
  filter(QuadID %in% plot_code_vector) %>%
  rename(Plot_code = QuadID) %>%
  column_to_rownames(var = "Plot_code") %>%
  as.matrix() 

# Species_list 
species_list <- read_excel("data/raw/Chalmandrier et al. 2022/data/complete_species_names.xlsx")

chalmandrier_clean <- lst(chalmandrier_cover, chalmandrier_trait, species_list, trait_information)

``` 

# Calculations
```{r chalmandrier calculations}

output <- prep_plotlvl(input_veg = chalmandrier_cover, input_trait = chalmandrier_trait, plot_code_vector, trait_information, 0.8) 

relative_abundances <- output[["relative_abundances"]]
cwm_cwv_all_traits <- output[["cwm_cwv_all_traits"]]
trait_data <- output[["trait_data"]]

```


## 5. Format output
```{r calculations }

processed_specieslvl <- lst(relative_abundances, cwm_cwv_all_traits, trait_data)

diversity_info <- processed_specieslvl[["relative_abundances"]][["matrix4traits_prop"]] %>% 
  as.data.frame() %>% 
  mutate(shannon = diversity(.[,1:ncol(.)], index = "shannon", MARGIN = 1, base = exp(1)),
         simpson = diversity(.[,1:ncol(.)], index = "simpson", MARGIN = 1, base =exp(1)),
         species_richness = specnumber(.[,1:ncol(.)], MARGIN = 1)) %>%
  select(shannon, simpson, species_richness) %>%
  rownames_to_column(var = "Plot_code") # base = exp(1) gives the shannon index a log e base

save(processed_specieslvl, diversity_info, trait_information, plot_code_vector,
  file = "data/processed/Char_processed.RData")


```


