---
title: "0.Preprocessing"
author: "Jelyn Gerkema"
date: "2023-06-20"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

## 0. Set up
```{r set up}
source("src/settings.R")
source("src/functions.R")

```

## 1.Clean data


### 1.1 Bergholz et al. 2020
```{r clean data}

bergholz_veg <- read_csv("data/raw/Bergholz et al. 2021/LocalAbundance.csv")

RegionalAbundance <- read_csv("data/raw/Bergholz et al. 2021/RegionalAbundance.csv")

traits <- read_csv("data/raw/Bergholz et al. 2021/traits.csv")

# Some species have no presence in any of the plots. They are filtered out.
bergholz_cover <- bergholz_veg %>% 
  select_if(~ !is.numeric(.) || sum(.) != 0) %>% # The code evaluates whether a column is numeric, if it is, the second statement is evaluated. 
  column_to_rownames(var = "plot") %>% 
  t() %>% # Flip the dataframe so the species become the rows and the sites the columns
  as.data.frame() %>%
  rownames_to_column(var = "Name") %>%
  arrange(Name) %>%
  column_to_rownames(var = "Name") %>%
  t() # The double transpose is so that I can arrange the dataframe in the alfabetic order of the species names. But I have to transpose it back so that the plot_codes are the rows and the species are the columns
   

# Extract the plot_codes
plot_code_vector <- rownames(bergholz_cover)

# In the study
# The species Anthemis tinctoria has no trait data for the SLA. Instead, the family average is taken based on available data. 
traits_clean <- traits %>%
  select(c(site, spec_name, SLA, LDMC, Height)) %>%
  rename(Name = spec_name) %>%
  group_by(Name) %>%
  summarise(across(where(is.numeric), ~mean(., na.rm = T))) %>%
  mutate_all(~ifelse(is.nan(.), NA, .)) %>%
  arrange(Name)

# To do so, the species list is extracted. This is used to pull up the hierarchical information using the lookup_table function.
species_list <- RegionalAbundance %>%
  pull(Species_long)

hierarchy <- lookup_table(species_list, by_species=TRUE, 
                          family.tax = "plantlist", missing_action = "drop") %>%
  rownames_to_column(var = "Species_long") %>%
  arrange(Species_long) %>%
  rowid_to_column("plant_id") %>%
  full_join(RegionalAbundance) %>%
  rename(Name = Species_short) %>%
  full_join(traits_clean) %>%
  filter(Name %in% colnames(bergholz_cover))

family_mean <- hierarchy %>%
  select(c(Name, genus, family, SLA )) %>%
  group_by(family) %>%
  summarise(across(where(is.numeric), ~mean(., na.rm = T))) %>%
  filter(family == "Compositae") %>%
  pull(SLA) 

bergholz_trait <- hierarchy %>%
  select(Name, Height, LDMC, SLA) %>%
  replace_na(list(SLA = family_mean)) %>%
  mutate(across(where(is.numeric), ~ c(scale(., center = FALSE)))) %>%
  arrange(Name)


traitlist <- c("Height", "LDMC", "SLA")
cwm_names <- paste0(traitlist, "_cwm")
cwv_names <- paste0(traitlist, "_cwv")

trait_information <- lst(traitlist, cwm_names, cwv_names)


bergholz_clean <- lst(bergholz_cover, bergholz_trait, species_list, trait_information)

``` 


## 5. Perform calculations
```{r calculations }

processed_specieslvl <- prep_studylvl(input_veg = bergholz_cover, input_trait = bergholz_trait,
                                      cutoff_value =  0.8, trait_information = trait_information)

diversity_info <- processed_specieslvl[["relative_abundances"]][["matrix4traits_prop"]] %>% 
  as.data.frame() %>% 
  mutate(shannon = diversity(.[,1:ncol(.)], index = "shannon", MARGIN = 1, base = exp(1)),
         simpson = diversity(.[,1:ncol(.)], index = "simpson", MARGIN = 1, base =exp(1)),
         species_richness = specnumber(.[,1:ncol(.)], MARGIN = 1)) %>%
  select(shannon, simpson, species_richness) %>%
  rownames_to_column(var = "Plot_code") # base = exp(1) gives the shannon index a log e base

save(processed_specieslvl, diversity_info, bergholz_clean, plot_code_vector, trait_information,
  file = "data/processed/Bergholz_processed.RData")


```







