---
title: "1. Data_analysis"
author: "Jelyn Gerkema"
date: "2023-07-11"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Set up 

```{r set up}

source("src/settings.R")
source("src/functions.R")
source("src/maxent2.R")
#source("src/maxenttest2.R")
source("src/maxenttest2_annotated.R")

load("data/processed/Bergholz_processed.RData")

```

## 2. Running the model 

### 2.1 Setting up multiple cores

```{r setting up cores}

#Determines amount of cores, substract four to keep to pc free for other processes.
n_cores <- parallel::detectCores() - 4 

my_cluster <- makeSOCKcluster(n_cores)

registerDoSNOW(cl = my_cluster)

foreach::getDoParRegistered() # check if cluster is set up

```

### 2.2 Running the CATS model

```{r actually runnin the model}


cats_output_berg <- cats_studylvl(prep_output = processed_specieslvl, 
                                  trait_information = trait_information)

unregister_dopar()


save(output_df, output_nmds, file = "data/processed/CATS_Bergholz.RData")

```

