---
title: "2. Visualisation"
author: "Jelyn Gerkema"
date: "2023-07-11"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 0. Set up
```{r set up}
source("src/settings.R")
source("src/functions.R")
load("data/processed/LVD_processed_V2.RData")
load("data/processed/LVD_cats_output.RData")
load("data/processed/LVD_cats_output_years.RData")
load("data/processed/LVD_cats_output_years_Bioland5000.RData")


LVD_ZL_species <- read_delim("data/raw/LVD_Zuid_Limburg_species.csv", 
    delim = "\t", escape_double = FALSE, 
    trim_ws = TRUE)



cats_output <- output_list$processed_specieslvl
calculations_cwm_cwv <- processed_specieslvl$calculations_cwm_cwv
```



## Preperation final 
```{r final figures}
cats_output <- output_df

cats_output_processed <- cats_output %>%
  mutate(
    just.neutral1 = model.prior.plus.traits - model.uniform.prior.plus.traits,
    just.neutral2 = model.mean.null.given.prior - model.mean.null.given.uniform,
    just.traits1 = model.uniform.prior.plus.traits - model.mean.null.given.uniform,
    just.traits2 = model.prior.plus.traits - model.mean.null.given.prior,
    information.unique.to.local.trait.constraints = just.traits2 / (1 - model.bias),
    information.unique.to.neutral.prior = just.neutral1 / (1 - model.bias),
    delta.R.trait = just.traits1,
    delta.R.neutral = just.neutral2,
    T1 = just.traits1 - just.traits2,
    T2 = just.neutral2 - just.neutral1,
    joint.information = T2 / (1 - model.bias),
    biologically.unexplained.information = (1 - model.prior.plus.traits ) / (1 - model.bias),
    check = information.unique.to.local.trait.constraints + information.unique.to.neutral.prior + joint.information +
    model.bias + biologically.unexplained.information
  ) %>%
  select(c(
    information.unique.to.local.trait.constraints, information.unique.to.neutral.prior,
    joint.information, biologically.unexplained.information, Plot_code, pval.meta, pval.uniform
  )) %>%
  pivot_longer(cols = 1:4, names_to = "Deviance", values_to = "KLR2") %>%
  mutate(Deviance = recode(Deviance,
    biologically.unexplained.information = "Unexplained effect",
    information.unique.to.neutral.prior = "Pure metacommunity effect",
    joint.information = "Joint trait & metacommunity effect",
    information.unique.to.local.trait.constraints = "Pure trait effect"
  ))

cats_output_combined <- list(diversity_info,
  calculations_cwm_cwv,
  cats_output_processed) %>%
  reduce(inner_join) 


ggplot(cats_output_combined, aes(x = species_richness, y = model.bias)) + geom_point()

cats_output_lambda <- cats_output %>%
  select(-c(
    model.bias, model.prior.plus.traits,
    model.mean.null.given.prior, model.uniform.prior.plus.traits,
    model.mean.null.given.uniform
  )) %>%
  pivot_longer(cols = 1:20, values_to = "Lambda", names_to = "Traits") %>%
  separate(Traits, into = c("Trait", "Model"), sep = " ") %>%
  filter(Trait != "prior" & Trait != "intercept")  


cats_output_lambda_combined <- list(
 diversity_info_V2, calculations_cwm_cwv,
  cats_output_lambda, LVD_header_clean) %>%
  reduce(inner_join) %>%
    filter(species_richness >= 9)


plot_trait_max <- cats_output_combined %>%
  filter(Deviance == "Pure trait effect") %>%
  filter(KLR2 > 0.15) %>%
  pull(Plot_code)




ggplot(cats_output_combined, aes(x = species_richness, y = KLR2)) +
  geom_point() +
  facet_wrap(~Deviance) + 
  theme_classic() +
  geom_smooth(method = "lm") + 
  labs(title = "The relationship between species richness and the CATS decomposition - Bergholz et al. 2020",
       x = "Species richness") +
  geom_hline(yintercept = 0, linetype = 2)


temp <- cats_output_combined %>% pivot_wider(names_from = Deviance, values_from = KLR2)

pivot
ggplot(temp, aes(y = `Pure trait effect`, x = `Pure metacommunity effect`, colour = species_richness)) + 
         geom_point() 



  

``` 

### Figures final
```{r figures final }


output_all_v2 <- PQ %>% 
  filter(Deviance == "Pure metacommunity effect") %>%
  relocate(KLR2)

output_all_v2 <- cats_output_combined %>% 
  filter(Deviance == "Pure metacommunity effect") %>%
  relocate(KLR2, n)

map_country("Netherlands", c(5.5, 6.2), c(50.7, 51)) + 
  geom_point(data = output_all_v2,  aes(y = `Y coordinate`, x = `X coordinate`, colour = KLR2, size = species_richness)) + ggtitle("De contributie van dispersie aan de samenstelling van plantengemeenschappen Zuid-Limburg") + 
  scale_color_gradient2(low="darkgreen", mid="yellow", high="purple", 
                        limits = c(0, 1), oob = scales::squish) + facet_wrap(~jaar) + 
  theme(legend.position = "bottom") +
  guides(size = guide_legend(title = "Soortenrijkdom"))


map_country("Netherlands", c(5.5, 6.2), c(50.7, 51)) + 
  geom_point(data = output_all_v2,  aes(y = `Y coordinate`, x = `X coordinate`, colour = n)) + ggtitle("De contributie van dispersie aan de samenstelling van plantengemeenschappen Zuid-Limburg") + 
  scale_color_gradient2(low="darkgreen", mid="yellow", high="purple", 
                        limits = c(1, 100), oob = scales::squish) + facet_wrap(~jaar) + 
  theme(legend.position = "bottom") +
  guides(size = guide_legend(title = "Soortenrijkdom"))


output_all_v2 <- cats_output_combined %>% 
  filter(Deviance == "Pure trait effect") %>%
  relocate(KLR2, n) 

map_country("Netherlands", c(5.5, 6.2), c(50.7, 51)) + 
  geom_point(data = output_all_v2,  aes(y = `Y coordinate`, x = `X coordinate`, colour = KLR2, size = species_richness)) + ggtitle("De contributie van selectie op soorteigenschappen aan de samenstelling van plantengemeenschappen Zuid-Limburg") + 
  scale_color_gradient2(low="darkgreen", mid="yellow", high="purple", 
                        limits = c(0, 1), oob = scales::squish) + facet_wrap(~jaar) + 
  theme(legend.position = "bottom") +
  guides(size = guide_legend(title = "Soortenrijkdom"))


output_all_v2 <- cats_output_combined %>% 
  filter(Deviance == "Unexplained effect") %>%
  relocate(KLR2, n) 

temp <- cats_output_combined %>%
  drop_na(Veg_habitat)

ggplot(temp, aes(x = species_richness, y = KLR2)) + 
  geom_point(alpha = 0.4, aes( colour = Veg_habitat)) + facet_wrap(~Deviance) + 
  #geom_vline(xintercept = 4, linetype = 2) +
  theme_classic() +
  geom_smooth(method = "lm") + 
  labs(title = "The relationship between species richness and the CATS decomposition",
       x = "Species richness") +
  theme(legend.position = "bottom") +
  guides(colour=guide_legend(nrow=5, title = "Habitat type"))

map_country("Netherlands", c(5.5, 6.2), c(50.7, 51)) + 
  geom_point(data = output_all_v2,  aes(y = `Y coordinate`, x = `X coordinate`, colour = KLR2, size = species_richness)) + ggtitle("Onverklaarde variatie in de samenstelling van plantengemeenschappen in Zuid-Limburg") + 
  scale_color_gradient2(low="darkgreen", mid="yellow", high="purple", 
                        limits = c(0, 1), oob = scales::squish) + facet_wrap(~jaar) + 
  theme(legend.position = "bottom") +
  guides(size = guide_legend(title = "Soortenrijkdom"))


output_all_v2 <- cats_output_combined %>% 
  filter(Deviance == "Joint trait & metacommunity effect") %>%
  relocate(KLR2, n) 


map_country("Netherlands", c(5.5, 6.2), c(50.7, 51)) + 
  geom_point(data = output_all_v2,  aes(y = `Y coordinate`, x = `X coordinate`, colour = KLR2, size = species_richness)) + ggtitle("De gezamelijke contributie van selectie en dispersie mechanismen aan de samenstelling van plantengemeenschappen in Zuid-Limburg") + 
  scale_color_gradient2(low="darkgreen", mid="yellow", high="purple", 
                        limits = c(-1, 1), oob = scales::squish) + facet_wrap(~jaar) + 
  theme(legend.position = "bottom") +
  guides(size = guide_legend(title = "Soortenrijkdom"))

table(output_all_v2$n)
  
tmp <- cats_output_combined %>%
  pivot_wider(values_from = "KLR2",
              names_from = "Deviance") %>%
  mutate(dif = `Pure trait effect` - `Pure metacommunity effect`) 

map_country("Netherlands", c(5.5, 6.2), c(50.7, 51)) + 
  geom_point(data = tmp,  aes(y = `Y coordinate`, x = `X coordinate`, colour = dif, size = species_richness)) + ggtitle("Het verschil in de relatieve contributie van selectie en dispersie aan de samenstelling van plantengemeenschappen in Zuid-Limburg") + 
  scale_color_gradient2(low="darkgreen", mid="yellow", high="purple", 
                        limits = c(-1, 1), oob = scales::squish) + facet_wrap(~jaar) + 
  theme(legend.position = "bottom") +
  guides(size = guide_legend(title = "Species richness"),
         colour = guide_colorbar(title = "Trait - Dispersal"))







ggplot(output_all_v2, aes(x = NMDS1, y = NMDS2, 
                          colour = KLR2)) + 
  geom_point() + 
  facet_wrap(~jaar, scales = "free") +
    theme_classic() +
  theme(legend.position = "bottom") +
    scale_color_gradient2(low="darkgreen", mid="yellow", high="purple", 
                        limits = c(0, 1), oob = scales::squish)

map_country("Netherlands", c(5.5, 6.2), c(50.7, 51)) + 
  geom_point(data = tmp,  aes(y = `Y coordinate`, x = `X coordinate`, colour = dif, size = species_richness)) + ggtitle("The difference in the relative contribution of selection and dispersal to local plant communities in Zuid-Limburg") + 
  scale_color_gradient2(low="darkgreen", mid="yellow", high="purple", 
                        limits = c(-1, 1), oob = scales::squish) + facet_wrap(~jaar) + 
  theme(legend.position = "bottom") +
  guides(size = guide_legend(title = "Species richness"),
         colour = guide_colorbar(title = "Trait - Dispersal"))


ggplot(output_all_v2, 
       aes(x = species_richness, y = KLR2, colour =  Veg_habitat)) + 
   geom_point(alpha = 0.3) +
  theme_classic() +
  #geom_hline(yintercept = 0, linetype = 2) +
  scale_y_continuous(breaks = c(0, 0.1, 0.2, 0.3, 0.4, 0.5,
    0.6, 0.7, 0.8, 0.9, 1
  )) +
  coord_cartesian(ylim = c(0, 1)) +
 # labs(x = NULL, title = "CATS model, different levels of biodiversity, data at species level") +
  theme(legend.position = "bottom") + 
   geom_smooth(method = "lm", se = F) +
  facet_wrap(~Veg_category) +
  guides(colour=guide_legend(nrow=8, title = NULL)) +
  labs(x = "Species richness", title = "Contribution of pure trait selection to local plant communities in Zuid-Limburg")



tmplambda <- cats_output_lambda_combined %>% 
  relocate(Model) %>% filter(Model == "fit1") %>%
  filter(Plot_code %in% plot_trait_max) %>%
  inner_join(cats_output_processed2) %>%
  relocate(information.unique.to.local.trait.constraints,
           Lambda, Trait) %>%
  drop_na(Veg_habitat)


lambda_summary <- tmplambda %>% 
  select(c(Veg_category, Plot_code)) %>%
  distinct() %>%
  group_by(Veg_category) %>% 
  tally()

lambda_summary_zoom <- tmplambda %>% 
  select(c(Veg_habitat, Plot_code, Veg_class_name)) %>%
  distinct() %>%
  drop_na(Veg_habitat) %>%
  group_by(Veg_habitat) %>% 
  tally()

lambda_summary_zoom2 <- tmplambda %>% 
  filter(Veg_habitat == "Zomen") %>%
  select(c(Veg_habitat, Plot_code, Veg_class_name)) %>%
  distinct() %>%
  drop_na(Veg_habitat) %>%
  group_by(Veg_class_name) %>% 
  tally()

tmplambda_zoom <- cats_output_lambda_combined %>% 
  relocate(Model) %>% filter(Model == "fit1") %>%
  filter(Plot_code %in% plot_trait_max) %>%
  inner_join(cats_output_processed2) %>%
  relocate(information.unique.to.local.trait.constraints,
           Lambda, Trait) %>%
  drop_na(Veg_habitat)# %>%
  filter(Veg_habitat == "Voedselarme, gesloten graslanden") 
  select(SM_cwm, WO_cwv, Lambda, Trait, Veg_habitat,
         Veg_class_name, species_richness) %>%
  filter(Trait == "SM_mean")

trait_variance <- cats_output_lambda_combined %>% 
  relocate(Model) %>% filter(Model == "fit1") %>%
  filter(Plot_code %in% plot_trait_max) %>%
  inner_join(cats_output_processed2) %>%
  relocate(information.unique.to.local.trait.constraints,
           Lambda, Trait) %>%
  drop_na(Veg_habitat) %>%
  select(SM_cwm, SM_cwv, Lambda, Trait, Veg_habitat,
         Veg_class_name, species_richness) %>%
  filter(Trait == "SM_mean")

tmplambda_zoom2 <- cats_output_lambda_combined %>% 
  relocate(Model) %>% filter(Model == "fit1") %>%
  filter(Plot_code %in% plot_trait_max) %>%
  inner_join(cats_output_processed2) %>%
  relocate(information.unique.to.local.trait.constraints,
           Lambda, Trait) %>%
  drop_na(Veg_habitat) %>%
  filter(Veg_habitat == "Zomen") 
  #select(WO_cwm, WO_cwv, Lambda, Trait, Veg_habitat,
      #   Veg_class_name, species_richness) %>%
  #filter(Trait == "WO_mean")

ggplot(trait_variance, aes(x = SM_cwv, y = Lambda, colour = species_richness)) +
  geom_point() +
  theme(legend.position = "bottom") + 
    facet_wrap(~Veg_habitat, scales = "free") +
  theme_classic() 

ggplot(tmplambda, aes(x = Veg_category, 
                      y = Lambda, colour = Veg_category)) +
  geom_boxplot(aes()) +
  facet_wrap(~Trait, scales = "free", 
             labeller = as_labeller(new_labels)) +
  theme_classic() +
  geom_hline(yintercept = 0, linetype = 2) +
  labs(title = "Vegetatie types", x = NULL ) + 
  theme(legend.position = "bottom") + 
  theme(
  axis.text.x = element_blank(), axis.ticks = element_blank()) +
  #geom_text(data = lambda_summary,
         #  aes(Veg_habitat, Inf, label = n), vjust = 11) +
    #guides(colour=guide_legend(nrow=6, title = "Vegetation class")) +
  guides(colour = guide_legend(title = "Vegatatie type", nrow = 2)) + 
  scale_x_discrete(labels = new_labels) +
  scale_colour_discrete(labels = paste0(lambda_summary$Veg_category, " (", lambda_summary$n, ")"))


ggplot(tmplambda_zoom, aes(x = Veg_habitat, 
                      y = Lambda, colour = Veg_habitat)) +
  geom_boxplot(aes()) +
  facet_wrap(~Trait, scales = "free", 
             labeller = as_labeller(new_labels)) +
  theme_classic() +
  geom_hline(yintercept = 0, linetype = 2) +
  labs(title = "Belang van soorteneigenschappen in verschillende habitats", x = NULL ) + 
  theme(legend.position = "bottom") + 
  theme(
  axis.text.x = element_blank(), axis.ticks = element_blank()) +
  #geom_text(data = lambda_summary,
         #  aes(Veg_habitat, Inf, label = n), vjust = 11) +
    #guides(colour=guide_legend(nrow=6, title = "Vegetation class")) +
  guides(colour = guide_legend(title = "Habitat", nrow = 4)) + 
  scale_x_discrete(labels = new_labels) +
  scale_colour_discrete(labels = paste0(lambda_summary_zoom$Veg_habitat, " (", lambda_summary_zoom$n, ")"))

ggplot(tmplambda_zoom2, aes(x = Veg_class_name, 
                      y = Lambda, colour = Veg_class_name)) +
  geom_boxplot(aes()) +
  facet_wrap(~Trait, scales = "free", 
             labeller = as_labeller(new_labels)) +
  theme_classic() +
  geom_hline(yintercept = 0, linetype = 2) +
  labs(title = "Zomen", x = NULL ) + 
  theme(legend.position = "bottom") + 
  theme(
  axis.text.x = element_blank(), axis.ticks = element_blank()) +
  guides(colour = guide_legend(title = "Habitat", nrow = 2)) + 
  scale_x_discrete(labels = new_labels) +
  scale_colour_discrete(labels = paste0(lambda_summary_zoom2$Veg_class_name, " (", lambda_summary_zoom2$n, ")"))

new_labels <- c("CH_mean" = "Canopy height", 
                "LM_mean" =  "Leaf mass", 
                "LMDC_mean" =  "Leaf dry matter content", 
                "PL_mean" =  "Plant life span", 
                "SLA_mean" = "Specific leaf area", 
                "SM_mean" =  "Seed mass", 
                "TV_mean" = "Terminal velocity", 
                "WO_mean" =  "Woodiness")


```




## 1. Preperation
```{r exporing output}

cats_output <- output_df

cats_output_processed <- cats_output %>%
  mutate(
    just.neutral1 = model.prior.plus.traits - model.uniform.prior.plus.traits,
    just.neutral2 = model.mean.null.given.prior - model.mean.null.given.uniform,
    just.traits1 = model.uniform.prior.plus.traits - model.mean.null.given.uniform,
    just.traits2 = model.prior.plus.traits - model.mean.null.given.prior,
    information.unique.to.local.trait.constraints = just.traits2 / (1 - model.bias),
    information.unique.to.neutral.prior = just.neutral1 / (1 - model.bias),
    delta.R.trait = just.traits1,
    delta.R.neutral = just.neutral2,
    T1 = just.traits1 - just.traits2,
    T2 = just.neutral2 - just.neutral1,
    joint.information = T2 / (1 - model.bias),
    biologically.unexplained.information = (1 - model.prior.plus.traits) / (1 - model.bias),
    check = information.unique.to.local.trait.constraints + information.unique.to.neutral.prior + joint.information +
    model.bias + biologically.unexplained.information
  ) %>%
  select(c(
    information.unique.to.local.trait.constraints, information.unique.to.neutral.prior,
    joint.information, biologically.unexplained.information, Plot_code, pval.meta, pval.uniform
  )) %>%
  pivot_longer(cols = 1:4, names_to = "Deviance", values_to = "KLR2") %>%
  mutate(Deviance = recode(Deviance,
    biologically.unexplained.information = "Unexplained effect",
    information.unique.to.neutral.prior = "Pure metacommunity effect",
    joint.information = "Joint trait & metacommunity effect",
    information.unique.to.local.trait.constraints = "Pure trait effect"
  ))



ggplot(cats_output_combined, aes(x = pval.uniform, 
                                  y  = information.unique.to.local.trait.constraints,
                                 colour = shannon)) +
  geom_point() +
 geom_vline(xintercept = 0.05, linetype = 2) +
geom_vline(xintercept = 0.95, linetype = 2) +
  geom_hline(yintercept = 0, linetype = 1) + 
  theme_classic() #+
  #theme(legend.position = "none") 
rm(resultaten)


tmp <- temp1$KLR2.null %>% as.data.frame() %>%
  rename(value = ".")

ggplot(tmp, aes(x= value)) + geom_histogram() + 
  geom_density(colour = "darkred", linewidth = 2) + theme_classic() +
 # geom_vline(xintercept = temp1$mean.KLR2.null, linetype = 1, colour = "darkblue", linewidth = 2) +
  geom_vline(xintercept = median(tmp$value), linetype = 1, colour = "darkgreen", linewidth = 2) +
  geom_vline(xintercept = temp1$obs.stat, linetype = 1, colour = "violet", linewidth = 2)

temp1$pval

cats_output_combined <- list(diversity_info_V2,
  calculations_cwm_cwv,
  cats_output_processed,
  LVD_header_clean,
  output_nmds) %>%
  reduce(inner_join) %>%
  filter(species_richness >= 9) # %>%
  #filter(`Opp. proefvlak (m²)` <= 300) %>%
  #mutate(Species_richness_bins = cut(species_richness,
   #                   breaks = c(8, 14, 19, 54),
    #                  include.lowest = T,
     #                 right = F))




ggplot(diversity_info, aes(species_richness)) + geom_histogram()

cats_output_lambda <- cats_output %>%
  select(-c(
    model.bias, model.prior.plus.traits,
    model.mean.null.given.prior, model.uniform.prior.plus.traits,
    model.mean.null.given.uniform
  )) %>%
  pivot_longer(cols = 1:20, values_to = "Lambda", names_to = "Traits") %>%
  separate(Traits, into = c("Trait", "Model"), sep = " ") %>%
  filter(Trait != "prior" & Trait != "intercept")  


cats_output_lambda_combined <- list(
 diversity_info_V2, calculations_cwm_cwv,
  cats_output_lambda, LVD_header_clean) %>%
  reduce(inner_join) %>%
    filter(species_richness >= 9) #%>%
  #filter(`Opp. proefvlak (m²)` <= 300) 


meta_data_output <- cats_output %>%
  separate(Plot_code, into = c("Year", "PlotID"), sep = " ", convert = TRUE) %>%
  filter(Year == 2020) %>%
  inner_join(plot_metadata) %>%
  group_by(Year) %>%
  count(Soil_Type_WRB, name = "Soil_type")

plots <- cats_output %>% pull(Plot_code)


MDS_input <- processed_specieslvl[["relative_abundances"]][["matrix4traits_prop"]] %>% 
  as.data.frame() 
  
MDS_input <-  MDS_input[rownames(MDS_input) %in% plots, ]

nmds_results <- metaMDS(comm = MDS_input, distance = "bray", try = 100)


nmds_scores <- as.data.frame(scores(nmds_results)$sites) %>%  rownames_to_column(var = "Plot_code") 




```



## test
```{r test}



map_country("Netherlands", c(5.5, 6.2), c(50.7, 51)) + geom_point(data = output_all_v2, size = 3, aes(y = Cal_Y, x = Cal_X, colour = Veg_class_name)) + ggtitle("LVD data from Zuid-Limburg") + facet_wrap(~jaar) + 
  theme(legend.position = "bottom")


```



## 2. Visualisation
```{r visualisation}

tmp <- cats_output_combined %>%
  separate(Plot_code, into = c("x", "y"))

ggplot(NDFF_all_v2, aes(Cal_X, Cal_Y, colour = KLR2)) + geom_point() +
  facet_wrap(~Deviance)

ggplot(NDFF_all, aes(centrumx, centrumy)) + geom_point() 



ggplot(tmp, aes(x = Deviance, y = KLR2, colour = Species_richness_bins)) + 
   geom_boxplot() +
  theme_classic() +
  geom_hline(yintercept = 0, linetype = 2) +
  scale_y_continuous(breaks = c(
    -0.6, -0.5, -0.4, -0.3, -0.2, -0.1, 0, 0.1, 0.2, 0.3, 0.4, 0.5,
    0.6, 0.7, 0.8, 0.9, 1
  )) +
  coord_cartesian(ylim = c(-0.5, 1)) +
  labs(x = NULL, title = "CATS model, different levels of biodiversity, data at species level") +
  scale_colour_manual(breaks = c("[8,14)",  "[14,19)", "[19,54]"),
                          values = c("[8,14)" = "#440154FF", 
                                     "[14,19)" = "#21908CFF",
                                     "[19,54]" = "#FDE725FF")) +
  labs(colour = "Species richness level") 

tmp <- cats_output_combined$ve %>% filter(species_richness < 32) %>% relocate(`Permanent Quadraat  (J/N)`)
tmp <- cats_output_combined %>% relocate(`Permanent Quadraat  (J/N)`)
tmp <- cats_output_combined %>% filter(Deviance == "Unexplained effect") %>%  relocate(NMDS1, Veg_class_name) 
tmp <- cats_output_combined %>% filter(Deviance == "Pure metacommunity effect") %>%  relocate(NMDS1, Veg_class_name) 
tmp <- cats_output_combined %>% filter(Deviance == "Pure trait effect") %>%  
  relocate(KLR2, Veg_class_name, pval.meta, pval.uniform, jaar) %>%
  mutate(KLR2_new = case_when(pval.meta > 0.05 ~ 0,
                              TRUE ~ KLR2))
  

ggplot(tmp, aes(x = shannon, y = KLR2)) + 
   geom_point(aes(colour = Veg_class_name)) +
  theme_classic() +
  geom_hline(yintercept = 0, linetype = 2) +
  scale_y_continuous(breaks = c(
    -0.6, -0.5, -0.4, -0.3, -0.2, -0.1, 0, 0.1, 0.2, 0.3, 0.4, 0.5,
    0.6, 0.7, 0.8, 0.9, 1
  )) +
  coord_cartesian(ylim = c(-0.5, 1)) +
 # labs(x = NULL, title = "CATS model, different levels of biodiversity, data at species level") +
  theme(legend.position = "botom") + 
  facet_wrap(~jaar) +
  geom_smooth(method = "lm") 


ggplot(tmp, aes(x = NMDS1, y = NMDS2, colour = pval.meta)) + geom_point(size = 2) + theme_classic() + theme(legend.position = "bottom") + 
  facet_wrap(~jaar, scales = "free")
tmp <- cats_output_combined %>% 
  relocate(model.bias, model.mean.null.given.prior, model.prior.plus.traits, model.uniform.prior.plus.traits)


tmplambda <- cats_output_lambda_combined %>% relocate(Model) %>% filter(Model == "fit1")

lambda_summary <- tmplambda %>% 
  select(c(Veg_class_name, Plot_code)) %>%
  distinct() %>%
  group_by(Veg_class_name) %>% 
  tally()



ggplot(tmplambda, aes(Veg_class_name, Lambda, colour = Veg_class_name)) +
  geom_boxplot() +
  facet_wrap(~Trait, scales = "free") +
  theme_classic() +
  geom_hline(yintercept = 0, linetype = 2) +
  labs(title = "Lambda's per vegetation class") + 
  theme(legend.position = "bottom") + 
  theme(
  axis.text.x = element_blank(), axis.ticks = element_blank()) +
  geom_text(data = lambda_summary,
            aes(Veg_class_name, Inf, label = n), vjust = 20)

Temp <- Output_all_KLR2 %>%
  separate(Plot_code, into = c("Year", "PlotID"), sep = " ", convert = TRUE) %>%
  inner_join(Plotdata_coor) %>%
  inner_join(Plotdata_landtype) %>%
  count(`Land use type`)


```